/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("com.github.node-gradle.node") version "2.2.4"
}

node {
    version.set("9.11.2")
    download.set(true)
}

tasks.register<Zip>("zip") {
    from(".") {
        include("*")
        include("bin/**")
        include("data/**")
        include("node_modules/**")
        include("public/**")
        include("routes/**")
        include("views/**")
    }
    destinationDirectory.set(file("dist"))
    archiveBaseName.set("trainSchedule")
    dependsOn("npm_build")
}

tasks.register<com.github.gradle.node.npm.task.NpmTask>("npmInstall") {
    setArgs(listOf("install"))
}

tasks.register<com.github.gradle.node.npm.task.NpmTask>("npm_build") {
    setArgs(listOf("run", "build"))
    dependsOn("npmInstall")
}

tasks.register<com.github.gradle.node.npm.task.NpmTask>("npm_test") {
    setArgs(listOf("test"))
    dependsOn("npmInstall")
}

tasks.named("build") {
    dependsOn("zip")
    dependsOn("npm_build")
}

tasks.named("npm_build") {
    dependsOn("npm_test")
}

